addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- scripts/upload-package.sh
- scripts/upload-executable.sh
before_install:
- scripts/install-stack.sh
- stack install hscolour
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
language: c
os:
- linux
- osx
script:
- stack --no-terminal build --bench --haddock --no-run-benchmarks --pedantic --test
- stack sdist
sudo: false
