addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- |
    if test "$TRAVIS_TAG" -a "$TRAVIS_OS_NAME" = 'linux'
    then
      mkdir -p "$HOME/.stack/upload"
      echo "{ \"username\": \"$HACKAGE_USERNAME\", \"password\": \"$HACKAGE_PASSWORD\" }" > "$HOME/.stack/upload/credentials.json"
      stack upload .
    fi
- |
    if test "$TRAVIS_TAG" -a "$GITHUB_TOKEN"
    then
      if test "$TRAVIS_OS_NAME" = 'linux'
      then
        curl --location 'https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2' > github-release.tar.bz2
      else
        curl --location 'https://github.com/aktau/github-release/releases/download/v0.6.2/darwin-amd64-github-release.tar.bz2' > github-release.tar.bz2
      fi
      gzip --best --to-stdout "$(stack path --local-install-root)/bin/octane" > "octane-$TRAVIS_OS_NAME.gz"
      tar -x --strip-components 3 -f github-release.tar.bz2
      ./github-release upload --user tfausak --repo octane --tag "$TRAVIS_TAG" --file "octane-$TRAVIS_OS_NAME.gz" --name "octane-$TRAVIS_OS_NAME.gz"
    fi
before_install:
- |
    mkdir -p "$HOME/.local/bin"
    export PATH="$HOME/.local/bin:$PATH"
    if test ! -f "$HOME/.local/bin/stack"
    then
      mkdir -p stack
      cd stack
      curl --location "https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64" > stack.tar.gz
      gunzip stack.tar.gz
      tar -x -f stack.tar --strip-components 1
      cp stack "$HOME/.local/bin/stack"
    fi
- stack install hscolour
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
env:
  global:
  - HACKAGE_USERNAME=fozworth
  - secure: Xr3cWH89oe0X72pBjZrPENv3AuVmsOCXSOKBTcjlt0zpvUbUjMTk859eTUCsbsM80MooneFeHo04nvM7Ev0FDuOCoxtQOaC5kgiECOpDuIgPHLi6Umlgo/h9nECwIrUQV2YQCeuuyJMXVX8G9YB0NS6xWYlaS86SRchoYSnhXvNl7KPfgBmgn6m2hwSTcj63nCXtmdIJrxPh2fn4El0eVZw644qlHEJf7eHCron34vGdrn50+zEk/Dz+ZGCUJwNMufKGuEkrUK1NkbulNnVmmvV+0T8UWMbCBfpospw+akyiRtf1v0upCJ4oUyq0AIbTgNTi5vEeY1u7oVar68ekQiyGkoOJT+OOkjGp7pt3m9nme6ten60D4mdjFOCCuXkKtYE9As/+8Kj5c3g2PgMZzUdipuZ3Stxg0HfY0+YbIqtQnw4pEnvWet7Q7g6coJpzd+eqOJq82BUBsdIXH43Cn+ZBJfU5/YwYSo/sepYwWBX2HwCwHb47Epvm9FF9ZiufZpx06dp6KzUDZjflDsJmXg2TPuLFPs54z9RMaaHyv0k2q+r5flrgVc988fdOw98nJaUjzV7VnyUcvnEpyy9yxhOoj6b7HoQ8qNMPiRFsYVVzcaFP0P0GNJ1c3YLiaN7rOkKvzjWcsQWOuv3Zkqtzeo5z7qts6hte92FfVIks9Cw=
  - secure: NJgTXZF8FCcKDVkQoKLoIDhNeC7V3w1qeW1M5sECqvgA3rqYksZgnuhBKLuN3gJqTeqrwoRkPjz2/otPrIMw07vGLhxpTvp0xmngdvvJ36b5MgH1GVMukAqHpa4+Zroak2aTYRqqSjwZgZmVUBKr5Tct4QtImZIsKKunM7bMuAI6T1enwrob024gAa+nTTCPF4l4OSdlluSGyf3NDM4j4qOc+f6NmIek1tGKy0hxgKSTvBsyTzvbXP2UD465Yvjs7TR1bi/0vA47NLyI0owzRDlvbBEKScnJ4L5ctYEqmI33M5lJkj8327BjHHI+DogtG07jWZ+52NO4tS2E2M433zCbzWfqL1XHpBYL/UgWXGsjJrwc/UhqEXWs+zAfebeOgybnEGpMnpafu+QUfN1F1f6yaAgE6IeYXHR9KfqYlTupOGDroa0v7kZ1pxorcLlxOVxBuTLO06tDZZwIdLnx87P/Re3r0a7ffD7iRcWj52Pp1z0cO7evYqCcY+ylUVB2F7K3xYNxfDDykvY/WDwTw5mh+DRp2qcUKIsJBYb1n7zRiI8wtIPJ4hL337aACzEbMOEen1yWsorwe4sevhTW5l27bx5s6vc5QFQujpbk/zJBJpitNlOhWWNLi50QvrQdxmr6neHsJHIbRjVp2bKd0y/unLpWZ4DB1tcqq/Yf8O8=
language: c
os:
- linux
- osx
script:
- stack --no-terminal build --bench --haddock --no-run-benchmarks --pedantic --test
- stack sdist
sudo: false
