addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- ! 'test $TRAVIS_TAG && mkdir -p $HOME/.stack/upload && echo "{ \"username\": \"$HACKAGE_USERNAME\"
  , \"password\": \"$HACKAGE_PASSWORD\" }" > $HOME/.stack/upload/credentials.json && stack
  upload .'
before_install:
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- test -f $HOME/.local/bin/stack || travis_retry curl -L https://www.stackage.org/stack/linux-x86_64
  | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
- stack install hscolour
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
language: c
script:
- stack --no-terminal build --bench --haddock --no-run-benchmarks --pedantic --test
- stack sdist
sudo: false
