addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- sh tools/upload-package.sh
- sh tools/attach-binary.sh
before_install:
- sh tools/install-stack.sh
- sh tools/install-github-release.sh
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
env:
  global:
  - HACKAGE_USERNAME=fozworth
  # HACKAGE_PASSWORD
  - secure: 'eZaoKlrOMrE1Wg7mD0eeKdZiMdQN5ogzPziJfRtTDY4Ei56mw0ItNNBef1RMt6nrs5ZgqhScddC4lLWIII7uuiZjfCrbib9J2Zmx9DgE8wMwFWnp3Tq+grvLdEbNjzidbQkEp8vl/ym/EZW868g1WEM8H0X8AZcoXTEqp1jzotOi9JZ/dt5lgOXVWHVJtsbmCqn3OBRbbdp7yau9DSY2tY4oZHT8bRRSu9UvQyE0EEY26YhDzIie9UJ1mlVKbSQOwDFfddd92t670kUCdNi86DQx//G4phg5a8hvjGxZMFYtOevUZ5OYkB3Ucho6ArNKT/VKb4yHL2Hj9C0S58NNm8wA8+4vEyBOaJUSGbLSKEQc+Njb1Oj/16+bxPpA5bdnCDtOKMUbe3CIkm+hny56/ca9yzmIlaq629PwVDiKyxGHDiSbTUK2RZPzIq2HMA3GUB3psBWr9FaMX1PV6brx8FfO88mlI1ziz6QnvhMmgE5VdDS2XZe9nnSDe3PzSXLQUqrX+7bp7R78XCgQfYDq5pEnHdQ/3U8kdpGEQOEf+QcemPnCVhdDCqGwUQ3vWO17p8z7fMEaywkv/zDViXECKMRFoJC9wdMAdJIOnRIpdtj7mPL5CzXveP2siSdl7/qFtNH08sbFta0OLf6PU8m6vEbtmvgvbI+XMNxNqtqjq0s='
  # GITHUB_TOKEN
  - secure: 'HRX4WVo1kQQNLdp8xMSFfcpWqpnY57AV8m3DlxeynlqsCgtydZDc+lLKCF61oq6YjZR67k+WEqR3WBF11SCBfjxRsh2ROOgFP3XC8oihcrLKv//jmDTCDbBR7DzNYKWmgcs0Xbrl9vjvFSsn5i0LcX5vSzcvmikbjQEP68cX/ZCQVsLs57buJGBhYShh1/tZ3h/K7MxbPfMLPG+SofHPmjuFjLECSXVIm+h2CaVU0p9LOpyVlfN/+fN6ToOl3cCA/6RSLaJC8qPFulT9PHK+1wcw9YmnVdoB4gfH4iiPlnrsM9vAvOkOdME88srvKRFVB1E2TD+v/9O1tYEydgNDEVXKrsnQ2SSy1oApTC4oEQ5z7wG+e+NauY1S8rAvlRqYvRibZo8Fq7hAHkeTFoEerTbA9LU2rZVUtmZqvrfvzAD2DrtLc0UZlrdF2VHR2ebc3/eRq5OZQKRp2hA0tdIG/sqO/R0/fV9Vicc46hVLFFc88A550hkLLWsxXygxUdz/bFpJBQk3TIysKsyLVwfmLSfK5+LLxvGDLtoILymTCV1DEzIuZKcW2kInLFTCl+KDoadJAjs5Bl0jS+c9J1BbPVcCZFiG+EIUScMwGpRZRjA0kVCFPTtciv8+Va3XawjE54aL7VdBbWF/zUL42ZMAZbplWCyJmAzKhJ8jHbj6RnM='
language: c
os:
- linux
- osx
script:
- stack setup
- stack build --bench --only-dependencies --test
- stack build --ghc-options -O2 --pedantic
- travis_wait stack build --pedantic --test
- stack build --bench --no-run-benchmarks --pedantic
- stack sdist
sudo: false
