addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- scripts/upload-package.sh
before_deploy:
- scripts/copy-executable.sh
before_install:
- scripts/install-stack.sh
- stack install hscolour
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
deploy:
- api_key:
    secure: vYH3XDZO7AVqcJl9+qVC6U1NeO7H7fv75ua/tQgc7J9SnZkyvotlVeNNSm4oHbirxZtExw1tHW+Nh/6vvKlgA7GmQ5NSHOMWC6tPlJFJgXXOiwvyF5ckkqZ8A4U60POkmRJxtiCDoLfjAtWN/ObDU97DgAp3t6Z36WbVYp8eh164B6YN/w5q9m0Zq8e6EBXcFBL49npfSJSBOFCz8Gd2wE2jvZHsVxPZwgdV4+KxblIf4fJEbb1pALkPX7OFniPpp11BHjtXxSeykH5KW7nfRGXqeX8dbddDJS4kzJJsCyJfDJli8hfUv5mfQMNuGXWW9bqs3wZoONDZJzcCYA8RF8IP7CaHKrNUh705+8IZFltZiVp94yKdPMzYCCB77n1SMQ72sxP6tz99jIYncGEIdvPCr21Y0kQekCSqoGhK51agbdYnBqopm7M3CiKBBS9lvrX6CpsX+K4HEzcEo/gZqsYZvSaOlOC+07v3kVorapjVLmWmAEhm5n8TjOR0rBOENC4On7vDDa+zlqAaUTBO+RcQstu2hU3qBA7bBM8evqQvaC6+ZiZanhvQL130G/8NSt2NA1JlXIh1yBoeRQHfX0Q1NigTU61cQDIa2x49CWVXRW2Bpo/biUiZ9DraonS5Aem7Jc2WYDmg2pP4TpFQiXO0r7ykxRl+/rZpOB6N98M=
  file: tmp/octane-$TRAVIS_OS_NAME
  on:
    repo: tfausak/octane
    tags: true
  provider: releases
  skip_cleanup: true
language: c
os:
- linux
- osx
script:
- stack --no-terminal build --bench --haddock --no-run-benchmarks --pedantic --test
- stack sdist
sudo: false
