build_script:
- stack.exe setup
- stack.exe --no-terminal build --bench --only-dependencies --test
cache:
- 'c:\s -> stack.yaml'
environment:
  GITHUB_TOKEN:
    secure: CTD2sGkh3EQaLuMJybGza6XNaI+Ews42mdNy9p3U+eShkrjIwYrbUVKnpzra8kIZ
  STACK_ROOT: c:\s
install:
- curl --output stack.zip --location --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe
on_success:
- ps: |
    if ($env:APPVEYOR_REPO_TAG_NAME)
    {
      ./stack.exe install github-release
      cp "$(./stack.exe path --local-install-root)/bin/github-release.exe" github-release.exe
      7z a octane.zip "$(./stack.exe path --local-install-root)/bin/octane.exe"
      ./github-release.exe upload --token "$env:GITHUB_TOKEN" --owner tfausak --repo octane --tag "$env:APPVEYOR_REPO_TAG_NAME" --file octane.zip --name "octane-$env:APPVEYOR_REPO_TAG_NAME-windows.zip"
    }
platform: x64
test_script:
- stack.exe --no-terminal build --bench --no-run-benchmarks --pedantic --test
- stack.exe sdist
version: '{build}'
