build_script:
- stack.exe setup
cache:
- 'C:\stack -> stack.yaml'
- 'C:\bin'
- '%LOCALAPPDATA%\Programs\stack\x86_64-windows\ghc-8.0.1.tar.xz'
environment:
  GITHUB_TOKEN:
    secure: CTD2sGkh3EQaLuMJybGza6XNaI+Ews42mdNy9p3U+eShkrjIwYrbUVKnpzra8kIZ
  PATH: '%PATH%;C:\bin'
  STACK_ROOT: 'C:\stack'
install:
- powershell -File tools/install-stack.ps1
- powershell -File tools/install-github-release.ps1
on_success:
- powershell -File tools/attach-binary.ps1
platform: x64
test_script:
- stack.exe build --bench --only-dependencies --test
- stack.exe build --ghc-options -O2 --pedantic
- stack.exe build --pedantic --test
- stack.exe build --bench --no-run-benchmarks --pedantic
- stack.exe sdist
version: '{build}'
