build_script:
- stack.exe setup
- stack.exe --no-terminal build --bench --only-dependencies --test
cache:
- 'c:/s -> stack.yaml'
- '%APPDATA%/local/bin'
- '%APPDATA%/local/programs/stack'
environment:
  GITHUB_TOKEN:
    secure: CTD2sGkh3EQaLuMJybGza6XNaI+Ews42mdNy9p3U+eShkrjIwYrbUVKnpzra8kIZ
  PATH: '%PATH%;%APPDATA%/local/bin'
  STACK_ROOT: c:/s
install:
- powershell -File tools/install-stack.ps1
- powershell -File tools/install-github-release.ps1
on_success:
- powershell -File tools/attach-binary.ps1
platform: x64
test_script:
- stack.exe --no-terminal build --bench --no-run-benchmarks --pedantic --test
- stack.exe sdist
version: '{build}'
