benchmarks:
  octane-benchmark:
    dependencies:
    - base
    - criterion ==1.1.*
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Game
description: Octane parses Rocket League replays.
executables:
  octane:
    dependencies:
    - base
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.markdown
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
github: tfausak/octane
library:
  dependencies:
  - aeson ==0.11.*
  - base ==4.9.*
  - binary ==0.8.*
  - bytestring ==0.10.*
  - deepseq ==1.4.*
  - vector ==0.11.*
  other-modules: Paths_octane
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: octane
synopsis: Parse Rocket League replays.
tests:
  octane-doctest:
    dependencies:
    - base
    - octane
    - doctest ==0.11.*
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: DocTest.hs
    source-dirs: test-suite
  octane-test-suite:
    dependencies:
    - base
    - octane
    - tasty ==0.11.*
    - tasty-hspec ==1.1.*
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.10.0'
