name: octane
version: 0.4.1

category: Game
description: Octane parses Rocket League replays.
extra-source-files:
- CHANGELOG.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: tfausak/octane
license: MIT
maintainer: Taylor Fausak
synopsis: Parse Rocket League replays.

library:
  dependencies:
  - base ==4.8.*
  - binary ==0.7.*
  - binary-bits ==0.5.*
  - bytestring ==0.10.*
  - containers ==0.5.*
  - data-binary-ieee754 ==0.4.*
  - deepseq ==1.4.*
  - text ==1.2.*
  other-modules:
  - Octane.Core
  source-dirs: library

executables:
  octane:
    dependencies:
    - base
    - octane
    main: Executable.hs
    source-dirs: executable

tests:
  octane-test-suite:
    dependencies:
    - base
    - binary
    - binary-bits
    - bytestring
    - containers
    - octane
    - tasty ==0.11.*
    - tasty-hspec ==1.1.*
    ghc-options: -threaded
    main: TestSuite.hs
    source-dirs: test-suite

benchmarks:
  octane-benchmark:
    dependencies:
    - base
    - binary
    - binary-bits
    - bytestring
    - containers
    - criterion ==1.1.*
    - octane
    ghc-options: -threaded
    main: Benchmark.hs
    source-dirs: benchmark
