category: Game
description: Octane parses Rocket League replays.
executables:
  octane:
    dependencies:
    - aeson
    - base
    - binary
    - bytestring
    - http-client >=0.4.30 && <0.6
    - http-client-tls >=0.2 && <0.4
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.markdown
- data/*.json
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
github: tfausak/octane
library:
  dependencies:
  - aeson >=0.11 && <1.3
  - base ==4.9.*
  - bimap ==0.3.*
  - binary ==0.8.*
  - bytestring ==0.10.*
  - containers ==0.5.*
  - data-default-class <0.2
  - file-embed ==0.0.*
  - overloaded-records ==0.4.*
  - rattletrap ==2.*
  - text ==1.2.*
  other-modules: Paths_octane
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: octane
synopsis: Parse Rocket League replays.
version: '0.19.0'
