benchmarks:
  octane-benchmark:
    dependencies:
    - base
    - binary
    - bytestring
    - containers
    - criterion ==1.1.*
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Benchmark.hs
    source-dirs: benchmark
category: Game
description: Octane parses Rocket League replays.
executables:
  octane:
    dependencies:
    - base
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Executable.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.markdown
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
github: tfausak/octane
library:
  dependencies:
  - aeson >=0.9 && <0.12
  - aeson-pretty ==0.7.*
  - autoexporter ==0.2.*
  - base >=4.8 && <4.10
  - binary >=0.7 && <0.9
  - binary-bits ==0.5.*
  - bytestring ==0.10.*
  - containers ==0.5.*
  - data-binary-ieee754 ==0.4.*
  - deepseq ==1.4.*
  - newtype-generics ==0.4.*
  - regex-compat ==0.95.*
  - regex-posix ==0.95.*
  - text ==1.2.*
  other-modules: Paths_octane
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: octane
synopsis: Parse Rocket League replays.
tests:
  octane-test-suite:
    dependencies:
    - base
    - binary
    - bytestring
    - containers
    - octane
    - tasty ==0.11.*
    - tasty-hspec ==1.1.*
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: TestSuite.hs
    source-dirs: test-suite
version: '0.4.24'
