benchmarks:
  octane-benchmark:
    dependencies:
    - base
    - binary
    - binary-bits
    - bytestring
    - containers
    - criterion ==1.1.*
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Benchmark.hs
    source-dirs: benchmark
category: Game
description: Octane parses Rocket League replays.
executables:
  octane:
    dependencies:
    - base
    - octane
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Executable.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: tfausak/octane
library:
  dependencies:
  - base ==4.8.*
  - binary ==0.7.*
  - binary-bits ==0.5.*
  - bytestring ==0.10.*
  - containers ==0.5.*
  - data-binary-ieee754 ==0.4.*
  - deepseq ==1.4.*
  - text ==1.2.*
  other-modules:
  - Octane.Core
  source-dirs: library
license: MIT
maintainer: Taylor Fausak
name: octane
synopsis: Parse Rocket League replays.
tests:
  octane-test-suite:
    dependencies:
    - base
    - binary
    - binary-bits
    - bytestring
    - containers
    - octane
    - tasty >=0.10 && <0.12
    - tasty-hspec ==1.1.*
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: TestSuite.hs
    source-dirs: test-suite
version: '0.4.6'
